spring.mongodb.uri=mongodb://localhost:27017/cloudshare

server.servlet.context-path=/api/v1.0

spring.data.mongodb.auto-index-creation=true

clerk.issuer=https://prepared-tiger-24.clerk.accounts.dev
clerk.jwks-url=https://prepared-tiger-24.clerk.accounts.dev/.well-known/jwks.json

clerk.webhook.secret=lzreLCSdHGuAI8qgatj37dwELglKEWDd